"""Alembic environment.

Two things here are worth calling out:

1. **The URL comes from application settings**, converted to a *blocking* driver
   via ``settings.sync_database_url``. Alembic's migration runner is synchronous,
   so pointing it at ``aiosqlite``/``aiomysql`` would fail. One ``DATABASE_URL``
   therefore configures both the app and migrations, and they cannot drift.

2. **``render_as_batch=True``** so autogenerated migrations work on SQLite, which
   has no real ``ALTER TABLE``. Alembic emulates it by creating a new table,
   copying rows, and swapping - without this, any column change breaks the moment
   someone runs migrations against the default dev database.
"""
from __future__ import annotations

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

# Importing the models package registers every table on Base.metadata, which is
# what `--autogenerate` diffs against.
import app.models  # noqa: F401
from alembic import context
from app.core.config import settings
from app.core.database import Base
from app.models.base import UtcDateTime

config = context.config


def render_item(type_: str, obj: object, autogen_context: object) -> str | bool:
    """Render the app's custom column types as plain SQLAlchemy types.

    Autogenerate would otherwise emit ``app.models.base.UtcDateTime()`` into the
    migration, which both needs an application import and - worse - couples a
    historical migration to code that may be refactored or deleted later. A
    migration should be a self-contained record of the schema at a point in time,
    so it is rendered as ``sa.DateTime()``: the exact type ``UtcDateTime``
    already emits (its UTC normalisation is Python-side only, with no DDL effect).
    """
    if type_ == "type" and isinstance(obj, UtcDateTime):
        return "sa.DateTime()"
    return False

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", settings.sync_database_url)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of executing it (``alembic upgrade --sql``).

    Useful when a DBA must review or apply the change by hand.
    """
    context.configure(
        url=settings.sync_database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        render_as_batch=True,
        render_item=render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply migrations against a live database."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # compare_type catches a VARCHAR(255) -> VARCHAR(512) widening, which
            # Alembic ignores by default.
            compare_type=True,
            compare_server_default=True,
            render_as_batch=True,
            render_item=render_item,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
